name: Build

on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.5.0-jdk17-alpine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs

  build-docker:
    runs-on: ubuntu-latest

    needs: build-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/libs

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Build Docker Image
        run: |
          docker build -t ms-lanchonetedarua-pagamento:latest .
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Push Docker image to ECR
        run: |
          # Login ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 468037464742.dkr.ecr.us-east-1.amazonaws.com
          
          # Image tag
          docker tag ms-lanchonetedarua-pagamento:latest 468037464742.dkr.ecr.us-east-1.amazonaws.com/lanchonetedarua:ms-lanchonetedarua-pagamento-latest
          
          # Publish image to ecr
          docker push 468037464742.dkr.ecr.us-east-1.amazonaws.com/lanchonetedarua:ms-lanchonetedarua-pagamento-latest
        env:
          AWS_DEFAULT_REGION: us-east-1
    